services:
  flask_app:
    build: .
    container_name: mi_backend_python
    expose:
      - "8080"
    environment:
      - TF_ENABLE_ONEDNN_OPTS=0

  nginx:
    image: nginx:latest
    container_name: mi_servidor_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask_app